pluginGroup = com.magento.idea.magento2plugin
pluginName = Magento PhpStorm
pluginRepositoryUrl = https://github.com/magento/magento2-phpstorm-plugin
pluginVersion = 2025.2.0
pluginSinceBuild = 250.*
pluginUntilBuild = 258.*
platformType = PS
platformVersion = 2025.1.3
platformPlugins = com.intellij.lang.jsgraphql:251.26927.39,org.jetbrains.junie:251.204.104
platformBundledPlugins = com.intellij.modules.json,com.jetbrains.php,JavaScript,com.intellij.copyright
gradleVersion = 8.10.2
kotlin.stdlib.default.dependency = false
org.gradle.configuration-cache = true
org.gradle.caching = true
