pluginGroup = com.magento.idea.magento2plugin
pluginName = Magento PhpStorm
pluginRepositoryUrl = https://github.com/magento/magento2-phpstorm-plugin
pluginVersion = 2025.2.0
pluginSinceBuild = 251.*
pluginUntilBuild = 258.*
platformType = PS
platformVersion = 252.18003.43
platformPlugins = com.intellij.lang.jsgraphql:252.18003.27
platformBundledPlugins = com.intellij.modules.json,com.jetbrains.php,JavaScript,com.intellij.copyright
gradleVersion = 8.10.2
kotlin.stdlib.default.dependency = false
org.gradle.configuration-cache = true
org.gradle.caching = true
