pluginGroup = com.magento.idea.magento2plugin
pluginName = Magento 2 and Adobe Commerce
pluginRepositoryUrl = https://github.com/magento/magento2-phpstorm-plugin
pluginVersion = 2026.2.2
pluginSinceBuild = 261.21525.38
pluginUntilBuild = 268.*
platformType = PS
platformVersion = 261.22158.208
platformPlugins = com.intellij.lang.jsgraphql:261.22158.185
platformBundledPlugins = com.intellij.modules.json,com.jetbrains.php,JavaScript,com.intellij.css,org.jetbrains.plugins.yaml,com.intellij.copyright,com.intellij.mcpServer
gradleVersion = 9.3.1
kotlin.stdlib.default.dependency = true
org.gradle.configuration-cache = true
org.gradle.caching = true
