# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run automated tests

on:
  pull_request:
    branches: [ master, '*-develop', 'mainline*' ]

jobs:

  testUI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            runIde: |
              export DISPLAY=:99.0
              Xvfb -ac :99 -screen 0 1920x1080x16 &
              gradle runIdeForUiTests &
          - os: windows-latest
            runIde: start gradlew.bat runIdeForUiTests
          - os: macos-latest
            runIde: ./gradlew runIdeForUiTests &

    steps:

      # Check out the current repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      # Set up Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Run IDEA prepared for UI testing
      - name: Run IDE
        run: ${{ matrix.runIde }}

      # Wait for IDEA to be started
      - name: Health Check
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://127.0.0.1:8082
          max-attempts: 15
          retry-delay: 30s

      # Run tests
      - name: Tests
        run: ./gradlew test

      - name: Capture Test Artifacts on Failure
        if: failure()
        run: |
          mkdir -p artifacts/videos
          latest_file=$(ls -Art video | tail -n 1)
          if [ -n "$latest_file" ]; then
            cp "video/$latest_file" "artifacts/videos/latest-test-video.mp4"
          fi
        shell: bash

      - name: Upload Test Video Artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: latest-test-video
          path: artifacts/videos/latest-test-video.avi

  static-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradle wrapper
        run: gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
      - name: Run Code Style Check
        run: ./gradlew checkstyleCI --no-daemon
        env:
          MODIFIED_FILES: ${{ steps.file_changes.outputs.files}}
          ACTIONS_STEP_DEBUG: true
      - name: Run PMD Quality Check
        run: ./gradlew pmdCI --no-daemon
        env:
          MODIFIED_FILES: ${{ steps.file_changes.outputs.files}}
